name: Deploy Static Page

on:
  push:
    branches:
      - master  # Change this to your default branch if it's different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: master
        folder: .   
