name: Deploy Static Page

on:
  push:
    branches:
      - master  # Change this to your default branch if it's different

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: master  # Change this to the branch you want to deploy to
        folder: .

  commit:
    needs: build_and_deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Commit Files
      run: |
        git config user.name "neeraj0001"
        git config user.email "np10121999@gmail.com"
        git add .
        git commit -m "Auto-commit changes"
        git push
