name: Manual Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build
      run: |
        # Add commands here to build your site
        # For example, if you're using Jekyll:
        # bundle install
        # bundle exec jekyll build

    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the built-in token
      run: |
        # Deploy to the "master" branch using GITHUB_TOKEN
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git config user.name "${{ github.actor }}"
        git checkout master
        git add .
        git diff-index --quiet HEAD || git commit -m "Deploy updates"
        git push origin HEAD:master

